/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 26.06.2026 10:43:32

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 3840;
#else
constexpr int kTensorArenaSize = 2816;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,975 } };
const TfArray<1, float> quant0_scale = { 1, { 0.054376803338527679, } };
const TfArray<1, int> quant0_zero = { 1, { -21 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 75, 13, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 75, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 38, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 38, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 304, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[5] = { -967, 317, 2472, -478, -489, };
const TfArray<1, int> tensor_dimension6 = { 1, { 5 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00015725256525911391, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[5*304] = { 
  -21, 14, -23, 6, -30, 55, -8, -28, 21, -46, 6, -14, 42, 37, -34, -23, 17, 7, -25, -14, -42, 27, -31, -14, 27, -6, 19, 3, 27, -5, -45, 11, 30, -6, -17, -46, 19, 1, -8, -8, -21, 25, -10, -30, 17, -23, 17, -22, -6, -49, -10, -33, 15, 17, 9, 10, 8, 28, -15, 41, 14, 15, 34, -26, -18, -14, -39, 7, 32, 13, -66, 38, 3, -6, 8, 16, 14, -72, -21, -58, -15, -13, -51, -1, 29, 8, -81, -8, -8, 11, 22, 1, 9, -66, -15, -28, -1, -3, -59, -40, 19, -23, -82, 3, -32, 8, 44, 17, 49, -83, -16, -17, -14, 5, -41, -32, 43, 22, -84, 6, -44, 18, 47, -32, 45, -32, -28, -39, -20, 28, -12, -2, 36, -3, -127, 5, -87, 32, 42, -70, 36, 28, -28, 7, -10, 15, 0, -12, 47, -61, -68, 10, -71, 39, 39, -73, -35, 32, -8, -2, -55, -10, 16, -13, 39, -11, -31, -15, 5, 34, 7, -11, -46, 44, -28, -8, -54, 8, -25, -12, 32, 30, -22, -9, 8, 16, 48, 13, -3, 6, -40, 1, -38, 10, 4, 0, 51, 52, -26, -6, 10, 7, 24, 12, 37, 49, -51, -41, -41, 17, 4, 16, 34, 32, 33, -6, 10, 20, 7, 14, 27, 1, -57, -18, -57, 10, -27, -2, -53, 15, 6, -25, 25, -25, 12, -5, 2, 6, -67, -8, -29, 28, 8, 18, -2, 12, -26, -18, 12, 21, -3, -10, 9, 23, -46, 1, -25, -3, 21, 18, 2, 18, 15, -31, 21, -4, -85, -27, 3, 37, -40, -18, -76, -45, -31, -7, -67, 30, 3, -25, 20, -64, -14, -5, 11, -3, -9, -62, -27, -12, 5, -92, -20, 12, -4, -19, -27, -104, -33, -51, 22, -14, -67, -91, 
  -1, 6, -32, 1, -11, 3, -68, 4, 18, -11, -10, 55, -8, 20, -21, -26, 25, 4, -17, -12, 4, -11, -37, -2, -30, -3, -4, -23, -9, 26, 48, -72, -15, -6, -2, 31, -2, -38, 14, 17, 12, -26, -37, -15, -34, -20, 47, -98, -28, 23, -49, 61, 0, 9, -53, -7, 14, -46, -2, 33, -46, -10, -1, -56, 1, -3, -10, 39, 0, -10, -9, 16, -32, -23, -26, -13, -42, 17, 39, -14, 23, -9, 8, 17, -7, -17, -12, 22, 1, -16, -8, -37, -4, -43, 24, -16, 16, -19, 25, -11, -56, -16, -32, 12, -52, -35, -25, -45, -9, 10, 48, -17, 23, -57, -24, 1, -69, -10, -52, 37, 3, -37, -60, -12, -69, -110, 45, -14, 20, -19, 16, 4, -44, 5, -29, 15, 22, -68, -10, 41, -13, -63, 35, -27, 18, -13, 22, 10, -90, 0, 0, 33, -18, -58, -44, 13, 2, -30, 49, -4, 4, 6, 16, 11, -28, 8, 8, -7, -5, -77, 11, -6, -11, -77, 22, 2, -36, 34, 7, 22, -82, 7, 44, 34, 14, -67, -24, 4, 1, -51, 1, 21, -34, 52, 17, 13, -24, -15, 2, 23, 2, -71, -24, -4, -42, -72, 8, 20, -55, 9, 30, 43, 8, -20, -12, 22, -31, -18, -18, -18, 5, 18, -14, 32, -25, 14, 49, 50, -19, -8, 8, 10, -22, -29, -30, -23, 12, -13, -35, 23, -50, -13, 25, 14, -10, -2, -7, 22, -3, -31, -46, -49, 20, 34, -4, 59, -49, -4, -9, 38, 0, 2, 29, -45, 13, -27, -52, 23, -37, 8, -43, 4, -28, -9, -8, -9, 21, 12, 10, -1, -6, -9, -37, 10, -1, 15, 11, -19, 16, -10, 1, -18, 27, -10, -25, -16, -15, 11, -76, -33, 5, 38, 21, -8, 
  45, -9, 15, -5, -45, -62, 81, -4, 16, 29, 41, -5, -7, 5, 14, 27, 17, -30, 10, -61, -24, -53, 37, -10, 15, 2, 38, 10, -37, -17, -15, 0, 3, -58, -5, -74, -39, -41, 19, 9, 29, 30, 62, 15, -86, -29, 5, -41, 24, -4, 19, -35, -67, -40, 5, 9, 24, -25, -4, 25, -52, -58, -26, -91, -7, -32, 3, -43, -76, -51, 58, -21, 16, -30, 22, 23, -27, 7, 3, -57, -10, 0, -20, -44, -52, -55, 14, -6, 40, -5, 54, 39, -27, -23, -35, -46, 3, 1, 5, -18, -27, -20, 38, -5, 29, 10, -1, 67, -79, -25, -36, 3, -17, -1, -16, -39, -45, -26, 23, -12, 41, 16, 61, 31, -12, -19, 10, -22, 2, -3, -27, -16, -52, 9, -11, 21, 36, -14, 43, 60, -11, -19, 2, -60, 38, 7, -2, -39, -27, 8, 39, -6, 21, -30, 36, 44, 3, -47, 4, -4, 37, 1, -33, -43, -15, -17, 3, -2, 24, 2, 27, 4, 25, -25, -1, -40, 30, -4, -55, -30, -84, -33, 32, -14, 6, -11, 5, 29, 19, -42, 21, -10, 22, -23, 12, -39, -63, -38, 9, -27, -3, -19, 4, 4, -36, -65, 3, -31, 16, -20, 21, -39, -46, -23, 58, -7, -4, -46, 38, 7, -8, -29, 14, -36, 21, 22, -16, -35, -55, -30, 21, -15, 1, -28, 1, 35, 18, 2, 25, -5, 50, -21, -13, -16, -68, -22, 59, 3, 68, -8, 35, 25, -52, -11, 10, -62, 31, 3, -6, -14, -52, -72, 25, -1, 11, -19, 32, 10, -14, 22, 34, -23, 38, -22, 9, 16, -55, -57, 9, 2, 22, -5, -20, 3, -25, -53, 12, 18, 48, -9, 9, 17, -84, -55, 72, 1, 36, 8, 52, 4, -80, -102, 27, 8, 
  7, 22, 31, 58, 5, 15, 18, 3, -2, 21, -21, -10, 2, -20, 28, 69, -21, -6, 5, 1, 27, 26, -17, 27, -4, -9, -10, -11, 12, -15, -38, 71, -30, 29, 22, -12, 18, 1, 17, 12, -2, -1, -56, -2, 18, 7, 23, 55, -33, 27, 14, -14, -5, 19, 8, 22, -3, 4, -8, 5, 14, 14, 16, 6, 8, -3, 7, -9, 18, 21, -46, 25, 3, -2, -31, -4, -11, 7, -6, 28, 9, 8, 0, -10, 19, 19, -34, 18, 32, 0, -38, 1, -3, 36, 19, 25, 2, 10, 6, 23, 30, 16, -18, 7, 33, 3, -23, 34, -20, -1, 19, 19, -5, 38, 26, 37, 9, 29, 15, 8, 16, 22, -52, 23, -71, 17, 2, 22, -21, 10, -12, 0, 15, 25, -13, 8, 14, 12, -45, 12, -81, 44, -14, 19, -15, 7, 5, 4, 10, 29, -6, 29, -12, 9, -35, 7, -33, 28, -10, 21, 3, -25, 13, -5, 4, 32, -29, -6, -25, 0, -34, -10, -2, 16, -18, -25, -5, 3, 1, -7, 19, 19, -34, 11, -41, 9, -13, 14, -15, 9, 8, 2, 5, -3, 4, 6, 8, 38, -16, 19, -5, 1, -45, 19, -2, 17, 6, -13, 22, -31, 5, 2, 11, 39, -10, 9, -14, -2, -40, 30, -42, 2, 15, -10, -24, 9, 22, 13, 20, 16, -4, 14, -6, -14, -42, -2, -23, 3, -5, -6, -8, 4, 21, -23, 22, 31, 3, -26, -6, 14, -24, -4, 13, 16, -9, 13, -2, -5, 35, 4, 21, 23, -20, 44, 11, 0, 8, -7, -12, -32, 17, 40, -21, 5, 20, 8, -3, 21, 17, 6, -17, 19, 13, 0, 12, -2, -5, 82, -18, 24, -10, 43, 6, 0, -10, 25, 5, -19, -37, 18, 11, 19, -32, 77, 
  -23, -8, -80, -78, -25, 9, -46, -21, -21, 3, -10, 2, 15, 28, -68, -61, -21, 8, -6, 71, -7, 9, -18, 19, -33, 4, -17, 7, -24, -12, -12, -76, -7, 12, 14, 52, 10, -10, -19, -8, -7, -11, 27, -12, -5, 41, -42, -17, -1, 17, 7, 7, 7, 17, -27, -20, -26, 4, -4, -39, 19, 28, -10, 49, -16, 20, 39, 13, 1, 1, 48, -7, 16, 19, -16, -14, 2, 30, -14, 25, -26, -12, 22, 11, -2, 4, 42, -22, -11, 9, 1, -74, 36, 38, -42, 12, 1, 20, 13, 25, -28, 9, 54, -6, -27, 2, -4, -70, 35, 53, -42, 10, -16, 3, 24, 38, -28, 11, 47, 24, -19, -27, 12, -19, 90, 40, -36, -7, -1, -10, 29, 6, 2, -41, 49, -25, -1, -25, -22, -18, 86, 24, -26, 5, 18, -38, 0, 1, -4, -9, 57, -28, 0, 16, -18, -36, -2, -49, -16, 1, 31, -33, 4, -24, 21, -52, 42, -50, -5, -9, -8, -62, 4, -12, -4, -3, 2, -24, -28, -13, 19, -49, 23, -39, 2, 24, -16, -33, -44, 11, -3, 16, 26, -31, -14, -1, 14, -20, -14, -13, -24, 29, 26, -63, 5, 13, 25, 18, 52, -4, -60, -46, 28, -25, -11, -10, -3, 19, 11, -86, 32, 9, 62, 30, 36, -27, -49, -66, 26, 1, -42, 8, -24, 9, 9, -53, 4, -20, 22, 24, 2, -31, -15, -70, 15, 20, -105, 17, 3, 17, 36, 17, -27, -21, 16, 22, 4, -18, -25, -98, 37, 7, -43, 22, -63, -3, 40, -44, 8, 2, 36, -33, 19, -14, 11, -87, 36, 13, -25, 9, 2, 52, 19, -24, 8, 10, 26, -27, 14, 12, -13, -68, 8, 3, -29, 3, -7, 40, 27, -11, 16, 7, 12, -37, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 5,304 } };
const TfArray<1, float> quant7_scale = { 1, { 0.006196427159011364, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -748, -1668, -1400, -2422, -1990, -1901, 257, -2086, -98, -1184, 347, 556, -578, -728, -757, -1793, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00010748717613751069, 0.00011571495269890875, 0.00019025908841285855, 0.0001940915099112317, 0.00015655443712603301, 0.00014080609253142029, 0.00020156371465418488, 0.00014831428416073322, 0.00013958945055492222, 0.00013300409773364663, 0.00022224530403036624, 0.00018469663336873055, 0.00019468432583380491, 0.00021290038421284407, 0.00024917387054301798, 0.00013485032832249999, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 19,-99,51,122,-39,-5,43,-84, -27,-107,38,8,-74,10,-10,-121, 58,-97,19,28,-40,-39,127,-76, 
  /* [1][0][][] */ -14,75,-59,28,1,-56,-32,45, -42,-47,-24,-50,37,86,-24,127, -39,9,39,-8,-47,-1,-83,-51, 
  /* [2][0][][] */ 12,-18,-13,1,15,-113,18,-13, 28,-7,2,-14,-12,-127,31,88, -14,44,-23,-57,-27,-67,38,-26, 
  /* [3][0][][] */ 13,-64,-8,-47,33,-57,-1,46, 29,-127,-22,0,3,-81,37,36, 31,-68,-45,-46,34,-80,34,66, 
  /* [4][0][][] */ -40,-34,14,-83,-66,-1,42,-1, -99,-6,10,-127,-33,30,22,-20, -38,95,6,-84,-51,127,-2,63, 
  /* [5][0][][] */ -53,44,-46,-16,25,-113,-62,30, -43,33,-112,4,64,-65,-22,-65, -76,127,-48,5,27,-26,-22,-40, 
  /* [6][0][][] */ 99,-110,-57,34,-50,-36,5,-26, 15,-127,-19,4,-43,-47,1,-32, 21,-98,1,49,-83,-26,-22,-70, 
  /* [7][0][][] */ -18,52,-127,-38,-52,5,26,30, -46,45,-87,-27,105,-32,29,6, -31,-11,-65,-66,92,-37,53,27, 
  /* [8][0][][] */ 81,-72,50,26,-16,-28,-33,-1, 10,-92,-69,94,111,-22,-127,22, -16,-22,41,45,-11,-9,-99,-19, 
  /* [9][0][][] */ -2,-117,69,-15,-74,127,7,-45, -63,-75,35,-63,-46,48,-44,-8, -62,-33,-42,-20,-43,8,-13,95, 
  /* [10][0][][] */ -43,-31,-38,18,-28,19,39,31, -90,-27,-61,27,-60,-32,7,11, -127,-33,-31,71,-56,43,17,24, 
  /* [11][0][][] */ -37,-61,6,57,48,14,-68,-17, -25,-93,5,-4,118,17,-82,-3, 29,-80,13,46,-4,-2,-127,-16, 
  /* [12][0][][] */ -42,64,-49,22,-44,-48,-94,-72, -24,-6,-60,-11,-45,-52,-119,-72, 5,37,-48,17,20,-127,-66,60, 
  /* [13][0][][] */ -31,18,0,-28,-127,40,-32,-46, -7,20,-8,-25,-55,-25,-23,-31, 25,-11,76,-43,4,-17,-44,102, 
  /* [14][0][][] */ -36,1,33,-27,-43,4,43,-67, -10,-7,39,-18,-18,-34,37,-108, 15,0,9,13,38,-49,-14,-127, 
  /* [15][0][][] */ 51,-52,53,-21,21,-45,-40,117, 11,-62,61,-55,-23,-29,-30,-12, 25,-104,90,-76,-127,-1,-21,42, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0027142299804836512, 0.0029219950083643198, 0.0048043583519756794, 0.0049011334776878357, 0.0039532599039375782, 0.0035555881913751364, 0.0050898189656436443, 0.0037451824173331261, 0.003524865722283721, 0.0033585745841264725, 0.0056120636872947216, 0.0046638972125947475, 0.0049161030910909176, 0.0053760888986289501, 0.0062920544296503067, 0.0034051951952278614, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -1327, -2658, -2993, -1734, -3769, -3914, -910, -3503, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 0.00019697670359164476, 0.00020798016339540482, 0.00019868361414410174, 0.00019208724552299827, 0.00021973809634801, 0.00016383113688789308, 0.00026958948001265526, 0.00020923760894220322, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*13] = { 
  /* [0][0][][] */ -4,66,1,-21,-4,-21,-51,-27,-106,15,85,-16,26, -1,-59,-63,-39,-36,-104,-124,-22,-127,-24,21,18,3, 3,-61,-57,-25,9,-10,-37,-52,-23,-9,78,32,62, 
  /* [1][0][][] */ -73,-110,-29,37,25,69,-68,127,-83,54,-26,8,5, -57,-71,-4,-17,4,75,-73,101,-76,60,-54,55,-47, -19,-95,7,-1,31,65,-47,79,-51,97,-41,11,-6, 
  /* [2][0][][] */ 12,77,-67,-55,-69,42,64,4,-15,-33,54,21,11, -64,51,-54,-21,-48,33,61,12,22,-56,54,87,-7, 7,17,-75,-89,-48,22,29,-26,88,-127,86,-16,7, 
  /* [3][0][][] */ -18,-14,1,-59,-15,-37,12,-12,-10,-61,1,-22,-3, 20,79,36,127,60,91,39,66,61,73,81,78,93, 59,-18,63,66,21,101,29,30,6,21,44,11,40, 
  /* [4][0][][] */ 127,-101,41,32,2,7,-28,-20,2,17,-15,-74,83, 125,-108,31,15,-7,-32,0,-46,44,-27,28,-32,57, 75,-82,26,5,-31,-12,5,-50,64,-18,24,-19,53, 
  /* [5][0][][] */ 66,76,-41,79,-21,26,-19,-11,67,69,-40,-52,-65, 56,40,-49,-10,13,38,59,-7,77,52,-122,-78,-77, -29,67,-96,28,-13,71,-15,86,87,10,-127,-102,67, 
  /* [6][0][][] */ 32,26,44,-4,-8,-10,-37,-8,-63,20,-33,-26,-60, 17,49,59,21,20,5,-10,33,23,36,-12,-55,-47, 18,37,127,14,-21,-18,-37,-31,-72,63,3,-32,-45, 
  /* [7][0][][] */ 0,-11,-2,102,-34,-68,-44,49,-27,-10,-17,-25,32, -48,-16,-6,109,4,-55,-28,84,-16,-53,31,4,12, -39,60,-57,127,-14,-93,-26,70,-24,-41,19,27,-44, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,13 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0036224399227648973, 0.0038247955963015556, 0.0036538303829729557, 0.0035325218923389912, 0.004041026346385479, 0.0030128865037113428, 0.0049578030593693256, 0.003847920335829258, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,75,13 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,75,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.03960135206580162, } };
const TfArray<1, int> quant13_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,75,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,38,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,38,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,38,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.025377940386533737, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,38,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,19,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,304 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,5 } };
const TfArray<1, float> quant21_scale = { 1, { 0.09551587700843811, } };
const TfArray<1, int> quant21_zero = { 1, { 19 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 976), (TfLiteIntArray*)&g0::tensor_dimension0, 975, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1520, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 312, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 975, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 976), (TfLiteIntArray*)&g0::tensor_dimension13, 600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 608), (TfLiteIntArray*)&g0::tensor_dimension15, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 608), (TfLiteIntArray*)&g0::tensor_dimension17, 608, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 608, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 608), (TfLiteIntArray*)&g0::tensor_dimension19, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 304), (TfLiteIntArray*)&g0::tensor_dimension21, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_924846_10_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_924846_10_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_924846_10_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_924846_10_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_924846_10_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
