/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 02.07.2026 12:58:40

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 3840;
#else
constexpr int kTensorArenaSize = 2816;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,975 } };
const TfArray<1, float> quant0_scale = { 1, { 0.046805933117866516, } };
const TfArray<1, int> quant0_zero = { 1, { -4 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 75, 13, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 75, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 38, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 38, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 304, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[5] = { -2339, -803, 2844, -40, 408, };
const TfArray<1, int> tensor_dimension6 = { 1, { 5 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00018911036022473127, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[5*304] = { 
  -63, -12, -37, -59, -77, -14, -12, -32, -24, -52, 19, -35, 43, -14, -31, -13, -17, -7, -17, -43, 1, -9, -7, -6, -12, 36, 21, 16, 14, 19, -9, -30, 16, -17, -27, -27, 16, -25, 33, 38, -35, 1, 34, 0, 14, -89, 12, -89, -34, -10, -39, -102, 18, -13, 11, 8, -11, 26, -7, 26, 6, 13, 11, -92, -49, -8, -33, -7, 61, -10, 8, -12, -11, 27, -15, 2, 6, -36, -40, -31, -40, -21, -53, -7, 36, -17, -22, -24, -7, 18, -4, -16, 18, -3, -19, -81, -29, 6, -39, -28, 21, -36, -10, -4, -4, 12, 10, 0, 26, -56, 10, 33, -14, 6, -84, -39, 22, -12, -101, -2, -6, 26, 35, -5, 58, 7, -47, -20, -6, 26, -33, 1, 34, -37, -84, -28, -28, 26, 44, -55, 0, 5, -88, 6, 12, 15, 15, -3, 41, -57, -61, -21, -74, 22, 14, -73, -95, 18, -16, -10, -59, 1, 16, -1, 20, 2, -11, -40, -24, 28, 24, -11, -15, 18, -90, -37, -78, 8, -22, 4, 18, 2, -5, -25, -12, 17, 30, 6, 86, 7, -65, -41, -62, -5, -4, -4, 29, 5, 8, -23, -32, 24, 3, 32, 28, 37, 0, -56, -52, -2, -2, 8, 34, 19, 18, -17, 25, 12, 18, 27, 55, 9, -3, -65, -80, -6, -12, 14, -31, 0, 2, -32, 3, -19, -45, 10, 14, 44, -9, -48, -46, 43, 10, -2, -10, 0, -23, -43, 9, 12, -6, 0, 19, 17, 35, 24, -37, 11, 13, 15, -24, -4, -4, -40, -17, -6, -46, -25, 24, 76, 5, -11, -7, -52, -5, 2, -70, 5, 1, -45, -14, -94, -43, -30, 10, -56, 3, -43, -62, -32, -24, -73, -46, 6, -8, -21, -22, -113, -34, -56, 32, -17, -15, -41, 
  54, -27, 16, -35, 12, 10, -23, 26, 38, -27, -14, 20, -9, 15, -2, -37, 50, -54, -12, -65, 12, -14, -26, 73, 14, -14, -18, -64, -23, -18, 15, -44, -6, -68, 1, -2, -1, -24, -29, 37, 28, -9, -47, -5, -37, -20, 25, -57, -19, 10, -45, 0, 2, 9, -64, 28, 22, -40, -20, 30, -47, -50, -3, 36, 6, -9, -13, 11, -36, 11, -43, 39, 9, -6, -41, -8, -18, -25, 6, 36, 23, 8, -28, 2, 34, 1, -31, 38, -19, 1, -6, 8, 12, -98, -5, 31, 14, -6, 2, 8, -52, -5, -32, 36, -54, -10, -16, 16, -8, -86, 19, 29, 1, -10, -5, 14, -48, 13, 15, 43, -29, -44, -47, 14, -64, -88, 33, 36, 12, 22, -3, -1, -54, 9, -22, 30, -30, -38, -47, 20, -52, -53, 41, 23, 19, 6, 13, 1, -65, 13, -2, 33, -9, -75, -38, 19, 11, -10, 30, 32, 14, -3, 17, -6, -50, 11, -9, -2, -11, -93, -12, 9, 8, -28, 14, 23, -60, 37, -6, 5, -33, 19, 28, 4, -12, -66, -3, 20, -37, -40, 18, 37, -30, 50, 2, 23, -31, 9, -26, -7, -3, -101, 0, 6, -35, -51, 17, 46, -34, 31, 10, 24, 1, -10, 19, -22, -32, -28, -52, 0, -22, -26, 40, 50, -44, 39, 24, 30, -30, -30, 13, -45, -17, -39, -7, -30, 10, -60, -1, 64, -50, 32, -8, 34, -23, -10, 13, 1, -14, -35, -8, -25, 7, 5, 20, 56, -24, 10, -13, 12, -9, 5, 9, -62, 5, -40, -84, -31, -30, -64, 8, 29, -58, -49, -6, -57, -10, 12, 20, 46, 12, -38, -43, -20, 4, 2, 32, -36, 21, -31, -7, 41, 24, -30, 3, 64, -13, -23, -10, -41, -13, 29, 46, -43, 
  -3, -15, -20, 20, -17, -1, 83, -12, 24, 14, 51, -48, -17, -2, 28, -31, 25, -19, -46, -6, -42, -14, 32, -9, 6, 15, 36, 3, -58, -16, 24, -15, -17, -48, -35, -58, -12, -46, 36, -32, 26, 17, 11, 3, -29, 35, 73, -19, -15, -10, -31, -33, -90, 0, 33, -20, 37, -5, -12, 38, -29, -4, 15, -45, 16, -40, -22, -20, -56, -39, 28, -30, -2, -46, -21, -29, -75, 33, 25, 8, -21, -23, -5, -60, -88, -24, 34, -52, 51, -18, -21, 18, -45, 12, 18, -25, -6, -53, -43, -42, -28, -19, 9, -45, 42, -13, -38, 29, -61, 19, 24, -25, -19, -26, -34, -48, -24, -25, 46, -12, -4, -11, 22, 8, -82, -27, 41, -14, -22, -33, -30, -20, -70, 14, 13, -12, 47, -47, 1, 34, 7, -1, 17, -59, -12, -43, -23, -48, -62, 5, 12, -19, 28, -35, 12, 24, 17, -47, -1, 5, 12, -29, -39, -41, -26, -18, 20, -29, 30, 9, 40, 7, -14, 0, 27, -27, 25, -53, -30, -42, -62, -18, 19, -7, 43, -38, 11, -7, -28, -6, 22, -11, 26, -44, 7, -22, -92, -13, 4, -1, 19, -23, -10, -13, -3, -3, 35, 25, 16, -25, 35, -35, -69, -4, 28, -17, 1, -62, 18, -33, -62, 2, 17, -37, -4, 19, 5, -60, -74, -20, 9, -25, 32, -51, -4, 1, -67, -21, 26, -21, 2, -14, 10, -42, -51, -8, 33, 9, 49, -34, 53, 40, -54, 13, -2, -16, 65, -6, -3, -15, -31, -52, 38, 13, 39, -19, 20, -8, -42, 8, 4, 2, 61, 11, -20, 12, -50, -58, 12, -8, 45, 11, 15, 0, -25, -41, 16, 4, 47, -6, -15, 24, -38, -63, 24, -23, 37, 17, 47, -13, -64, -80, 1, -45, 
  35, 60, 23, 60, 2, 19, -32, 3, -11, 51, -18, 10, -17, 7, -24, 41, -15, 11, 32, 6, -10, 23, -13, -8, -17, -20, -18, 6, 19, -2, -33, 30, -3, 26, 28, -2, 18, 11, -3, 1, -7, -14, -9, 1, 14, -7, -23, 32, -8, 1, 27, 6, 13, 26, -19, -4, -19, 7, -14, 1, 9, 9, -14, -13, -5, 9, 10, -5, 7, 19, -9, 25, 5, -3, -4, 30, 10, -3, -6, -3, 10, -9, 3, -2, 13, 22, -21, 24, 13, 9, -3, 12, 12, 6, -1, 0, 16, 22, 13, 16, 15, 25, 0, 11, 22, 12, -6, 16, -17, 5, -15, 19, 7, 16, 21, 23, 7, 17, -12, 15, 30, 23, 1, 15, 17, 3, -17, 2, -9, -7, 1, -4, 8, 2, -20, 12, 15, 12, -9, 19, 39, 19, -27, 7, -14, 4, 5, -8, 0, 17, 4, 26, -5, 20, -3, 7, 11, -1, -20, 3, 11, -2, 4, -11, 14, 14, -31, 6, -14, -1, -26, -4, 21, 2, -9, -11, 6, -1, -15, -7, 17, 13, -29, 31, -14, 5, -35, 23, 1, 15, 9, 17, -2, -2, 6, 0, 19, 24, -14, 27, 0, 5, -23, 14, 12, 6, -2, -13, 7, -17, 7, 7, 13, 30, -14, 47, 2, -4, -27, 20, 26, -6, 5, 19, 8, -6, 11, 15, 9, 18, -7, 49, -12, -4, -13, -8, 20, -14, -5, 17, -6, -29, 23, 6, 19, 23, -9, 20, -8, 16, -21, -10, -4, 31, -26, -4, -13, -4, 26, 22, 5, 23, -17, 53, -10, 6, 19, 25, -4, -18, -6, -9, -20, 21, 15, 40, 0, 21, 4, -14, -21, 20, 2, 22, 12, 53, -21, 89, -22, 53, 18, -3, -23, 21, -7, -13, -17, -2, -46, 32, 1, -35, -67, 55, 
  -101, -28, -61, -46, -22, 2, -7, -35, -21, -23, -27, 26, 28, 18, -5, 38, -69, 21, -12, 64, 13, 10, -30, -24, -18, -11, 4, 10, -13, -7, -20, 12, -15, 50, 22, 40, -14, -2, -13, -22, -23, 9, -11, -24, 1, 39, -26, 5, 19, 30, 26, 29, -10, 2, 19, -2, -7, -3, 34, -57, 21, 20, 13, -5, 9, 12, 42, 18, -11, -1, 21, -16, -3, -17, 15, -22, -1, 18, 20, -10, 0, 8, 38, 17, -59, -16, 7, -33, 0, -52, 10, -88, -3, 44, -18, 19, -14, 10, 23, 16, -4, 0, 12, -15, -42, -27, 19, -39, 36, 62, -20, -41, -18, 10, 26, 39, -17, 9, 22, 3, -1, -37, -21, -31, 13, 36, -6, -22, -1, 2, 33, 14, 5, 4, 26, -15, -3, -19, -11, -18, -15, 19, 5, -26, 22, -28, -3, 17, 12, -23, 46, -11, -22, 13, -2, -33, -54, -19, 18, -22, 16, -41, 12, 7, 26, -42, 30, -17, -9, 10, -1, -100, -50, -19, -4, -36, 7, -7, 15, 7, 12, -40, 22, -22, -24, 31, 16, -49, -67, -7, -33, -23, 37, -6, 3, -9, 13, -8, -20, 4, 1, 13, 7, -117, -32, -5, -28, -23, 43, -17, -48, -24, 25, -35, -9, -12, -37, 26, 39, -56, -57, 10, -15, -2, 30, -27, -33, -59, 37, 19, -20, 27, -4, 13, 1, -11, -8, 25, -32, -55, 36, -51, -10, -125, 10, 21, -73, -14, 11, 21, 9, 0, -3, -42, -38, -39, -21, -55, -14, -125, 40, 5, -27, 8, -7, 2, 20, -31, -4, -5, 10, -22, -10, -36, 12, -127, 47, 17, -20, -7, -4, 42, 25, -13, 9, -23, 10, -44, 22, -10, -9, -111, 9, 2, 2, -11, 1, 28, -14, -10, 20, 70, 33, 21, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 5,304 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0081541910767555237, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -931, -2887, -393, -3171, -2443, -1043, 847, -2233, -364, -1816, 363, -1990, -1770, -308, 771, -2743, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 0.00014625171024817973, 0.00016817321011330932, 0.0002373410970903933, 0.00016477610915899277, 0.00016510093701072037, 0.00012021574366372079, 0.00019076470925938338, 0.00025259470567107201, 0.00017549515177961439, 0.00017297526937909424, 0.00023600709391757846, 0.00021610806288663298, 0.00022206298308447003, 0.00018832544446922839, 0.00017519583343528211, 0.0002074120711768046, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ -23,-88,97,-7,-44,4,47,-57, -24,-3,-38,-16,-86,18,107,-127, 16,2,12,-4,-121,-10,-34,-78, 
  /* [1][0][][] */ -114,10,-16,-22,13,-13,-2,0, -56,-85,-14,-6,28,27,9,127, 11,-25,-12,-31,-6,-11,7,-37, 
  /* [2][0][][] */ -6,27,-15,-7,-18,-70,56,-15, -4,-8,-17,-25,-13,-127,-7,67, 1,34,-33,-23,-16,-63,9,-11, 
  /* [3][0][][] */ -18,-24,-23,-47,33,-75,28,44, 24,-94,-32,15,11,-102,55,18, 43,-35,-31,6,-10,-127,22,90, 
  /* [4][0][][] */ -45,-58,-20,-74,-87,-54,19,18, -16,-9,0,-127,-44,125,-28,-5, -47,74,-7,-70,-47,-5,-39,49, 
  /* [5][0][][] */ -34,55,-63,-19,-62,-127,-53,31, -38,15,-61,0,124,-68,6,-14, -30,105,-58,-9,27,-31,0,23, 
  /* [6][0][][] */ 49,-120,-9,49,-32,-46,9,2, 29,-114,18,-36,-35,-92,-9,13, 20,-127,-57,54,-48,-23,-4,-55, 
  /* [7][0][][] */ -70,17,-127,-33,-26,-5,66,-65, -62,4,-88,-33,34,-8,8,-43, -33,-3,-82,-16,32,-14,70,-60, 
  /* [8][0][][] */ -12,-127,33,66,12,-22,-82,11, -31,-106,-44,87,20,-31,-84,-10, 10,-40,105,-4,-6,-21,-70,-11, 
  /* [9][0][][] */ 12,-127,27,8,-31,105,-17,-23, -45,-93,31,-37,-13,-4,-22,-10, -108,-11,-5,-68,-58,16,-7,7, 
  /* [10][0][][] */ -50,-12,65,-7,-33,-8,-8,-2, -127,-63,-50,27,-14,-19,-6,18, -106,-6,-31,22,-45,38,-4,-4, 
  /* [11][0][][] */ 10,-24,-23,-5,-4,17,-34,-19, -16,-2,9,-1,127,2,-77,3, 3,5,12,15,-22,-14,-53,-4, 
  /* [12][0][][] */ 22,6,-25,34,43,-81,-80,-43, 4,-16,-17,14,-10,-92,-91,-91, 15,58,4,13,-8,-127,-73,-99, 
  /* [13][0][][] */ 23,1,1,-80,-121,27,-1,-61, 2,-5,11,-32,-74,4,-127,-62, -27,-28,15,-39,19,-43,-15,117, 
  /* [14][0][][] */ 5,-20,23,-68,-99,-20,-79,-127, -23,-20,25,-34,-59,-50,-12,-80, 77,-27,40,32,60,-61,-15,-103, 
  /* [15][0][][] */ 2,27,-30,6,86,-31,-22,19, -75,-27,2,-42,-4,-10,-3,27, -127,-126,14,-97,5,2,3,26, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0042708530090749264, 0.0049110059626400471, 0.0069308518432080746, 0.0048118038102984428, 0.0048212893307209015, 0.0035105487331748009, 0.0055707246065139771, 0.0073762889951467514, 0.0051248217932879925, 0.0050512361340224743, 0.006891896016895771, 0.0063108028843998909, 0.0064846989698708057, 0.0054994928650557995, 0.0051160813309252262, 0.0060568619519472122, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -914, -4660, -3657, -3321, -7153, -7010, -5938, -5698, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 0.00020922972180414945, 0.00017709287931211293, 0.00021745802951045334, 0.00014614469546359032, 0.00017422760720364749, 0.00016265512385871261, 0.00017836972256191075, 0.00017099874094128609, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*13] = { 
  /* [0][0][][] */ -19,66,-8,-58,-46,20,-55,-56,-7,-13,62,19,37, -73,-61,39,-48,-34,15,-48,-62,1,-19,42,-14,38, -66,-127,-107,-81,-23,-19,-2,-36,-1,-7,12,-8,18, 
  /* [1][0][][] */ -31,-75,22,39,40,61,-117,104,-57,44,-52,-14,-29, -11,-86,-6,8,31,65,-43,94,-88,74,-66,33,-46, 7,-102,17,2,18,80,-75,76,-74,127,-91,11,-34, 
  /* [2][0][][] */ 49,-52,-127,-44,-42,-43,-32,3,-2,2,-11,30,-5, 14,-40,-11,-47,-18,-34,-20,40,-16,-19,-18,-13,-22, 17,-126,-79,-65,-36,-41,-42,41,1,-11,-36,-13,-45, 
  /* [3][0][][] */ 5,-26,12,5,-17,-28,-46,6,34,-77,50,111,106, 69,55,63,81,89,107,57,23,33,58,92,60,57, 78,-94,-19,19,-8,127,25,-73,-2,-39,-27,84,30, 
  /* [4][0][][] */ 94,-127,62,-16,18,31,-54,-21,-26,33,13,-75,95, 124,-119,42,49,-5,-20,-35,-44,30,-13,20,-63,91, 124,-85,13,56,-50,-18,-33,-45,56,-20,4,-37,85, 
  /* [5][0][][] */ 55,56,20,25,-16,28,2,-85,28,89,-23,-51,-113, 61,46,-21,2,-23,43,47,-84,79,45,-80,-95,-23, 72,101,-77,28,-55,21,59,-21,127,8,-83,-114,-35, 
  /* [6][0][][] */ 63,112,78,-30,-75,-50,25,-52,-90,4,19,14,-58, 34,66,62,-4,-45,-21,39,-10,-67,-5,39,-12,-22, 42,18,78,-21,-76,12,36,0,-127,23,18,14,-24, 
  /* [7][0][][] */ -15,17,-59,113,-2,-87,-50,91,-21,-49,26,-28,16, -8,35,-36,118,7,-61,-52,63,-65,-28,-10,7,-4, -33,48,-48,76,27,-127,-62,18,-52,-50,25,52,-33, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,13 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0044701537117362022, 0.0037835561670362949, 0.00464595016092062, 0.0031223539263010025, 0.0037223401013761759, 0.0034750963095575571, 0.0038108357694000006, 0.0036533561069518328, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,75,13 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,75,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.034244146198034286, } };
const TfArray<1, int> quant13_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,75,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,38,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,38,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,38,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.023191798478364944, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,38,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,19,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,304 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,5 } };
const TfArray<1, float> quant21_scale = { 1, { 0.10657156258821487, } };
const TfArray<1, int> quant21_zero = { 1, { 14 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 976), (TfLiteIntArray*)&g0::tensor_dimension0, 975, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1520, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 312, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 975, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 976), (TfLiteIntArray*)&g0::tensor_dimension13, 600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 600, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 608), (TfLiteIntArray*)&g0::tensor_dimension15, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 608), (TfLiteIntArray*)&g0::tensor_dimension17, 608, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 608, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 608), (TfLiteIntArray*)&g0::tensor_dimension19, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 304, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 304), (TfLiteIntArray*)&g0::tensor_dimension21, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 5, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_924846_10_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_924846_10_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_924846_10_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_924846_10_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_924846_10_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
